apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qayawc0q1-go
  janus-idp.io/tekton: qayawc0q1-go
  backstage.io/kubernetes-id: qayawc0q1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qayawc0q1-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
